services:
  mysql:
    image: mysql:latest
    expose:
      - ${DATABASE_PORT}
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   expose:
  #     - 6379

  api:
    build:
      context: .
      dockerfile: relational.e2e.Dockerfile
    env_file:
      - env-example-relational
    # ports:
    #   - "3000:3000"
    environment:
      PAYLOAD_PRIVATE_KEY: ${PAYLOAD_PRIVATE_KEY}
      ETH_NATIVE_NETWORK: ${ETH_NATIVE_NETWORK}

